package com.example.connie.movieapp;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Created by Connie on 1/30/2017.
 */
public class MovieData implements Parcelable{ //class for Movie objects (MovieData)
    private String poster_path;
    private boolean adult;
    private String overview;
    private String release_date;
    private int[] genre_ids;
    private double id;
    private String original_title;
    private String title;
    private String original_language;
    private String backdrop_path;
    private double popularity;
    private double vote_average;
    private double vote_count;
    private boolean video;

    /**
     * @return path to movie poster
     */
    public String getPosterPath(){
        return poster_path;
    }
    /**
     * @return if its an adult movie or not
     */
    public boolean isAdult() {
        return adult;
    }
    /**
     * @return overview of movie
     */
    public String getOverview() {
        return overview;
    }
    /**
     * @return release date of movie
     */
    public String getReleaseDate() {
        return release_date;
    }
    /**
     * @return genre id
     */
    public int[] getGenreIds() {
        return genre_ids;
    }
    /**
     * @return movie id
     */
    public double getId() {
        return id;
    }
    /**
     * @return title of movie
     */
    public String getTitle(){
        return title;
    }
    /**
     * @return language of movie
     */
    public String getLanguage() {
        return original_language;
    }
    /**
     * @return vote count
     */
    public double getVoteCount() {
        return vote_count;
    }
    /**
     * @return vote average
     */
    public double getVoteAverage(){
        return vote_average;
    }
    /**
     * @return original title of movie
     */
    public String getOriginalTitle() {
        return original_title;
    }

    public String getBackdropPath() {
        return backdrop_path;
    }

    public double getPopularity() {return popularity; }

    public boolean isVideo() {
        return video;
    }


    //for test case, check if gson conversion works by checking if given movie equals the gson format
    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof MovieData)) {
            return false;
        }
        MovieData other = (MovieData) obj;
        return (other.poster_path.equals(poster_path) &&
                other.adult==adult &&
                other.overview.equals(overview) &&
                other.release_date.equals(release_date) &&
                other.genre_ids[0]==genre_ids[0] &&
                other.id==id &&
                other.original_title.equals(original_title) &&
                other.title.equals(title) &&
                other.original_language.equals(original_language) &&
                other.backdrop_path.equals(backdrop_path) &&
                other.popularity==popularity &&
                other.vote_average==vote_average &&
                other.vote_count==vote_count &&
                other.video==video);
    }

    /* The code below this line was automatically generated by the Parcelable AndroidStudio plug-in
     *      https://github.com/mcharmas/android-parcelable-intellij-plugin
     *  See: http://corochann.com/fast-easy-parcelable-implementation-with-android-studio-parcelable-plugin-641.html
     *      for an explanation.
     */
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(""+ this.vote_average);
        dest.writeString(this.title);
        dest.writeString(this.overview);
        dest.writeString(""+this.popularity);
        dest.writeString(this.poster_path);
        dest.writeString(this.release_date);
    }

    public MovieData() {
    }

    protected MovieData(Parcel in) {
        this.vote_average = Double.parseDouble(in.readString());
        this.title = in.readString();
        this.overview = in.readString();
        this.popularity = Double.parseDouble(in.readString());
        this.poster_path = in.readString();
        this.release_date = in.readString();
    }

    public static final Creator<MovieData> CREATOR = new Creator<MovieData>() {
        @Override
        public MovieData createFromParcel(Parcel source) {
            return new MovieData(source);
        }

        @Override
        public MovieData[] newArray(int size) {
            return new MovieData[size];
        }
    };
}

